version: "3"
services:
  certbot:
    build: .
    image: ${ORGANIZATION}/${CONTAINER}:${BUILD_TAG}
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    networks:
      - core

networks:
    core:
