version: "3"
services:
  certbot:
    build: .
    image: ${ORGANIZATION}/${CONTAINER}:${BUILD_TAG}
    container_name: ${CONTAINER}
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certbot:/etc/letsencrypt
    networks:
      - overlay

networks:
    overlay:
